package com.jarvis.assistant.home

import kotlinx.serialization.Serializable
import java.util.UUID

/**
 * One configured smart-home integration endpoint.
 *
 * Deliberately Android-free and serializable, mirroring `McpServerConfig`. This
 * record carries NO secret: tokens/passwords live in `util/SecretVault` under a
 * key derived from `(id, field)`, so a config export never leaks a credential.
 *
 * Every field except [id] carries an honest default so a forward-compatible
 * payload that omits a field still decodes (see [HomeConfigCodec]).
 *
 * @property id stable, non-empty identity; generated by [create] and never
 *   recomputed (vault keys and discovery caches bind to it).
 * @property provider the [HomeProviderId.id] this config speaks.
 * @property order deterministic position in the user's list; [create] appends.
 * @property metadata provider-specific NON-SECRET settings (e.g. Tuya `region`
 *   and `uid`). Empty for providers that need none. Never place a credential
 *   here — secrets live in the vault, keyed by `(id, field)`.
 */
@Serializable
data class HomeProviderConfig(
    val id: String,
    val provider: String,
    val enabled: Boolean = true,
    val baseUrl: String = "",
    val order: Int = 0,
    val metadata: Map<String, String> = emptyMap(),
) {
    companion object {
        /** Create a new config with a fresh stable [id], appended to [existing]. */
        fun create(
            provider: HomeProviderId,
            baseUrl: String,
            enabled: Boolean = true,
            existing: List<HomeProviderConfig> = emptyList(),
        ): HomeProviderConfig = HomeProviderConfig(
            id = UUID.randomUUID().toString(),
            provider = provider.id,
            enabled = enabled,
            baseUrl = baseUrl,
            order = nextOrder(existing),
        )

        /** The order a newly appended config should take. */
        fun nextOrder(existing: List<HomeProviderConfig>): Int =
            (existing.maxOfOrNull { it.order } ?: -1) + 1
    }
}
