package com.jarvis.assistant.mcp

import kotlinx.serialization.Serializable
import java.util.UUID

/**
 * How a configured MCP server is reached.
 *
 * `REMOTE` is an internet endpoint and is held to an https-only, public-host
 * policy (see [McpUrlPolicy]); `LOCAL` is a loopback-only server (the cleartext
 * exception) for on-device integrations.
 */
enum class McpServerKind { REMOTE, LOCAL }

/**
 * What a server may do on the user's behalf.
 *
 * `READ` is the default for a newly added server: a WRITE server can mutate
 * remote state, so it must be an explicit opt-in. This is a pure policy label;
 * enforcement lives in a later wave.
 */
enum class McpAccess { READ, WRITE }

/**
 * One configured MCP server.
 *
 * The record is deliberately Android-free and serializable so it can be
 * persisted, exported and (later) synced. It stores only the NAME of the auth
 * header — never the secret value, which lives in the vault under a key derived
 * from [id] (the header name alone is not sensitive).
 *
 * Every field except [id] carries an honest default so a forward-compatible
 * payload that omits a field still decodes (see [McpServerConfigCodec]).
 *
 * @property id stable, non-empty identity of the server. Generated by [create]
 *   and never recomputed: auth-vault keys and tool namespaces bind to it.
 * @property order deterministic position in the user's list; `create` appends.
 */
@Serializable
data class McpServerConfig(
    val id: String,
    val displayName: String = "",
    val kind: McpServerKind = McpServerKind.REMOTE,
    val url: String = "",
    val enabled: Boolean = true,
    val access: McpAccess = McpAccess.READ,
    val authHeaderName: String = "",
    val order: Int = 0,
) {
    companion object {
        /**
         * Create a new server with a freshly generated stable [id], appended to
         * [existing] (next order = highest existing order + 1, so a gap left by
         * a deletion never causes a collision).
         */
        fun create(
            displayName: String,
            kind: McpServerKind,
            url: String,
            enabled: Boolean = true,
            access: McpAccess = McpAccess.READ,
            authHeaderName: String = "",
            existing: List<McpServerConfig> = emptyList(),
        ): McpServerConfig = McpServerConfig(
            id = UUID.randomUUID().toString(),
            displayName = displayName,
            kind = kind,
            url = url,
            enabled = enabled,
            access = access,
            authHeaderName = authHeaderName,
            order = nextOrder(existing),
        )

        /** The order a newly appended server should take. */
        fun nextOrder(existing: List<McpServerConfig>): Int =
            (existing.maxOfOrNull { it.order } ?: -1) + 1
    }
}
